#!/usr/bin/env python3

"""Python file setter.

    This script allows the user to create a file with the python shebang:
    #!/usr/bin/env python3 line, and gives execute permissions for the users
    creator. Ready to code!? Then you can run your python file like this:
        ./foo. Without the .py extension.

    This script needs you to pass a file name. Like this: script.py or script.
    Works with both. And should be used like this: lvimpy --file script.
    Alternatively you can add an alias in bashrc or zshrc, depending on your
    Linux "shell" (bash or ksh), like this:
        alias lp='lvimpy --file'. So you can use this way: lp script

    You don't need to install any modules for this script to work.
"""

import argparse
from argparse import Namespace
import os
import stat
from pathlib import Path
import subprocess

shebang = "#!/usr/bin/env python3"


def check_shebang(file_path: str) -> bool:
    """Gets file path and checks shebang on the first line in file

    :param file_doc: The path for for the file to check
    :type file_path: str
    :returns: True if shebang written in file, otherwise False
    :rtype: bool
    """

    try:
        with open(file_path, "r") as input_file:
            line = input_file.readline()
            if line == shebang:
                return True
    except IsADirectoryError as dir:
        file_path_list = file_path.split("/")
        file = file_path_list[-1]
        print(f"{file}: {dir.strerror}")
        return False

    return False


def lvim_editor(file_path):
    """Gets file path to open it with lvim (Lunar Vim)

    :param file_path: The path for the file to open with lvim
    :type file_path: str
    :returns: None, it returns nothing
    :rtype: None
    """

    path = Path(file_path)
    if not path.is_dir():
        subprocess.run(["lvim", file_path])


def rename(file_path):
    """Gets file path to get the file to rename

    :param file_path: The path for the file to rename
    :type file_path: str
    :returns: None, it returns nothing
    :rtype: None
    """

    if file_path.endswith(".py"):
        file_path = Path(file_path)
        file_without_suffix = file_path.with_suffix('')
        subprocess.run(["mv", file_path, file_without_suffix])


def get_arguments() -> str:
    """Gets the arguments from command line, it parsers them

    :param: Gets no arguments
    :type None
    :returns: Returns a Namespace object with all the command line arguments
    :rtype: Namespace
    """

    parser = argparse.ArgumentParser(
        prog="pylunarvim",
        description=(
            "Creates a file with exec rights for the owner and, "
            "and writes a python shebang at the beginning of "
            "the the file."),
        epilog="Thanks for using %(prog)s! :)")
    parser.add_argument("--file", type=str)
    args: Namespace = parser.parse_args()

    if not args.file:
        parser.print_help()
        parser.exit()

    return args.file


def exec_rights(is_py_file, file_path):
    """If it's a python file, then gives exec flags on file for the user that
    creates it

    :param is_py:file: Flag to know if it's a python file
    :type is_py_file: bool
    :param file_path: File path for the file to change its exec mode
    :type file_path: str
    :returns: None, it returns nothing
    :rtype: None
    """

    if is_py_file and file_path:
        os.chmod(file_path, stat.S_IXUSR | stat.S_IRUSR | stat.S_IRWXU)


def touch(file_path):
    """Gets file path and touches it. If the does not exist, it creates it

    :param ile_path: File path for the file to create or touch
    :type file_path: str
    :returns: None, it returns nothing
    :rtype: None
    """

    Path(file_path).touch()


def shebang_write(file_path: str):
    """Gets file path, searches it for the files at the end of the path and
    writes a sheband in it

    :param file_path: File path for the file to open for writing shebang
    :type file_path: str
    :returns: None, it returns nothing
    :rtype: None
    """

    if os.stat(file_path).st_size == 0:
        with open(file_path, "w+") as out_file:
            out_file.write(shebang)


def locate_file(file_arg: str) -> str:
    """Gets file argument in file_arg variable, and locates it on file system,
    then return the full path where is located.

    :param file_arg: Relative file path argument to locate
    :type file_arg: str
    :returns: str with the full path of the located file
    :rtype: str
    """

    script_dir = os.path.dirname(__file__)  # <-- absolute dir the script is in
    rel_path: str = file_arg
    abs_file_path: str = os.path.join(script_dir, rel_path)

    return abs_file_path


def run() -> None:
    """Execute all the processes to acomplish the task of creating a file with
    a shenbang in it and give execution rights for user

    :param void
    :type void, no arguments are given
    :returns: None, it returns nothing
    :rtype: None
    """

    args: str = get_arguments()
    file_path: str = locate_file(args)

    if file_path:
        touch(file_path)
        shebang_write(file_path)
        line = check_shebang(file_path)
        exec_rights(line, file_path)
        rename(file_path)
        lvim_editor(file_path)


if __name__ == "__main__":
    run()
